# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a7894b19c577fb6c5d3f6af685afe9feb7102709c55d0b1f4a9b50566e6835120352a92607b39be0d1d777e1627f2b004dc4dc9b6b22ee896649d8e65c8825c

test:
  secret_key_base: 6ad39b0bec2228da3d271258ca1587f4cfba3382705780f2a19123d73196a44882dc0bbdeba703d1ef832ab423e07f5179e647faee7b1f6fd6799f720fb825ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
