# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 104053f893771a031d070e8455b7683acf35bdb522c991d53316647d8fb2cb2d2661a1f1bd3fbe8b64f55de186218c7deacb692cbda6339497099de1b03b8514

test:
  secret_key_base: c9754233336ae72359ccba73f53a5a599a902c86dae1b5282e54cd82403ae0182757c44eb848f9d6c34964817c9db9f3a6174f8fb46e7cf36a72d8c68a3fb920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
