# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4cb9c16eb26cebe690ac9c1db59518884a20608164e0e0858a80bfc52b9a3ce087af8b69866a58287080e601a07bc7577cf21b9932ab6f4cbb0195b4eebdb31

test:
  secret_key_base: 78844a9432766b810114ea7950e559b058ea30904aee6cc34cd8c1831b281a476b0664567c7ba202d3a8c49c00047aefe526167a1705c346dcf179815e92eb8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
