# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 682548bbdd5895a8fd2c0ccae92237b26723dab201076024ba614c0670ea11b65b49cf57cb62d105b57739f42481a975d4a3788c6f7597b483899e96d638b9ba

test:
  secret_key_base: 2d55e8174bd2d6f04187973a1ab6c0acb8f1020d9d6b915f3ed494619fe53cdf8a24a532935f8dfed9640cea41b8377bc6c96ed778af850d00cf725165b0b5b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
